In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../DATA/Advertising.csv')

In [4]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [5]:
X = df.drop('sales', axis=1)

In [6]:
y = df['sales']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_other , y_train, y_other = train_test_split(X,y,test_size=0.3 , random_state=101)

In [9]:
X_eval , X_test , y_eval, y_test = train_test_split(X_other,y_other,test_size=0.5 , random_state=101)

In [10]:
len(X_train)

140

In [11]:
len(X_eval)

30

In [12]:
len(X_test)

30

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
X_train = scaler.transform(X_train)

In [17]:
X_test = scaler.transform(X_test)

In [18]:
X_eval = scaler.transform(X_eval)

In [19]:
from sklearn.linear_model import Ridge

In [20]:
model1 = Ridge(alpha = 100)

In [21]:
model1.fit(X_train,y_train)

Ridge(alpha=100)

In [22]:
y_eval_pred = model1.predict(X_eval)

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mean_squared_error(y_eval , y_eval_pred)

7.320101458823871

In [25]:
model2 = Ridge(alpha = 1)

In [26]:
model2.fit(X_train,y_train)

Ridge(alpha=1)

In [27]:
y_eval_pred = model2.predict(X_eval)

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
mean_squared_error(y_eval , y_eval_pred)

2.383783075056986

In [30]:
y_final_pred = model2.predict(X_test)

In [31]:
mean_squared_error(y_test , y_final_pred)

2.254260083800517

In [32]:
X_train , X_test , y_train, y_test = train_test_split(X,y,test_size=0.3 , random_state=101)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()

In [35]:
scaler.fit(X_train)

StandardScaler()

In [36]:
X_train = scaler.transform(X_train)

In [37]:
X_test = scaler.transform(X_test)

In [38]:
model = Ridge(alpha = 100)

In [39]:
from sklearn.model_selection import cross_val_score

In [42]:
scores = cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv = 5)

In [44]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [45]:
abs(scores)

array([ 9.32552967,  4.9449624 , 11.39665242,  7.0242106 ,  8.38562723])

In [46]:
abs(scores.mean())

8.215396464543607

In [59]:
model1 = Ridge(alpha = 1)

In [70]:
scores = cross_val_score(model1,X_train,y_train,scoring='neg_mean_squared_error',cv = 10)

In [71]:
abs(scores.mean())

3.323018143114126

In [72]:
scores

array([-2.96250773, -3.05737833, -2.1737403 , -0.83303438, -3.46401792,
       -8.2326467 , -1.90586431, -2.76504844, -4.98950515, -2.84643818])

In [73]:
model1.fit(X_train,y_train)

Ridge(alpha=1)

In [74]:
y_final = model1.predict(X_test)

In [75]:
mean_squared_error(y_final,y_test)

2.319021579428752

In [76]:
from sklearn.model_selection import cross_validate

In [77]:
model = Ridge(alpha =100)

In [86]:
scores = cross_validate(model , X_train,y_train,scoring=['neg_mean_squared_error', 'neg_mean_absolute_error'],cv =10)

In [87]:
scores = pd.DataFrame(scores)

In [88]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.000996    0.000000                    -6.060671   
1  0.000000    0.001023                   -10.627031   
2  0.000991    0.000918                    -3.993426   
3  0.000000    0.000995                    -5.009494   
4  0.000997    0.000000                    -9.141800   
5  0.000000    0.000982                   -13.086256   
6  0.000000    0.000997                    -3.839405   
7  0.000000    0.000996                    -9.058786   
8  0.000997    0.000000                    -9.055457   
9  0.000989    0.000000                    -5.778882   

   test_neg_mean_absolute_error  
0                     -1.810212  
1                     -2.541958  
2                     -1.469594  
3                     -1.862769  
4                     -2.520697  
5                     -2.459995  
6                     -1.451971  
7                     -2.377395  
8                     -2.443344  
9                     -1.899797

In [89]:
scores.mean()

fit_time                        0.000497
score_time                      0.000591
test_neg_mean_squared_error    -7.565121
test_neg_mean_absolute_error   -2.083773
dtype: float64

In [95]:
model = Ridge(alpha = 1)

In [96]:
scores = cross_validate(model , X_train,y_train,scoring=['neg_mean_squared_error', 'neg_mean_absolute_error'],cv =10)

In [100]:
scores = pd.DataFrame(scores)

In [101]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.000997    0.000996                    -2.962508   
1  0.001102    0.000000                    -3.057378   
2  0.000000    0.000000                    -2.173740   
3  0.000000    0.000921                    -0.833034   
4  0.000000    0.000992                    -3.464018   
5  0.000996    0.000000                    -8.232647   
6  0.000994    0.000000                    -1.905864   
7  0.000000    0.000988                    -2.765048   
8  0.001239    0.000000                    -4.989505   
9  0.000000    0.000000                    -2.846438   

   test_neg_mean_absolute_error  
0                     -1.457174  
1                     -1.555308  
2                     -1.238770  
3                     -0.768938  
4                     -1.434489  
5                     -1.494316  
6                     -1.081362  
7                     -1.250011  
8                     -1.580971  
9                     -1.223326

In [102]:
scores.mean()

fit_time                        0.000533
score_time                      0.000390
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [103]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [104]:
y_final_p = model.predict(X_test)

In [106]:
mean_squared_error(y_final_p , y_test)

2.319021579428752