In [22]:
text = ['This is a line' , 'This is another line' , 'Completely different line']

In [33]:
from sklearn.feature_extraction.text import CountVectorizer ,TfidfTransformer

In [37]:
cv = CountVectorizer()

In [38]:
spaarse_matrix = cv.fit_transform(text)

In [39]:
spaarse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [40]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [41]:
tfidf = TfidfTransformer()

In [42]:
spaarse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [44]:
results = tfidf.fit_transform(spaarse_matrix)

In [46]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
tv = TfidfVectorizer()

In [49]:
tv_result  = tv.fit_transform(text)

In [50]:
tv_result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])