In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv("Advertising.csv")

In [23]:
X = df.drop('sales',axis = 1)
y = df['sales']


In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [25]:
poly_con = PolynomialFeatures(degree = 3, include_bias= False)

In [26]:
poly_feat = poly_con.fit_transform(X)

In [27]:
X.shape

(200, 3)

In [28]:
poly_feat.shape

(200, 19)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(poly_feat, y, test_size=0.3, random_state=101)

In [31]:
X_train.shape

(140, 19)

In [32]:
X_train.shape

(140, 19)

In [33]:
X_test.shape


(60, 19)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()

In [36]:
scaler.fit(X_train)

StandardScaler()

In [37]:
X_train = scaler.transform(X_train)

In [38]:
X_test = scaler.transform(X_test)

In [39]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [40]:
poly_feat[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [41]:
from sklearn.linear_model import Ridge

In [42]:
ridge_model = Ridge(alpha = 10)

In [43]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [44]:
test_pre = ridge_model.predict(X_test)

In [45]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error


In [46]:
MAE= mean_absolute_error(y_test,test_pre)

In [47]:
MAE

0.5774404204714175

In [48]:
MSE = mean_squared_error(y_test,test_pre)

In [49]:
MSE

0.8003783071528408

In [50]:
RMSE = np.sqrt(MSE)

In [51]:
RMSE

0.8946386461319681

In [52]:
from sklearn.linear_model import RidgeCV

In [53]:


ridgecv_model = RidgeCV(alphas=(0.1,1,10),scoring='neg_mean_squared_error')

In [54]:
ridgecv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [55]:
ridgecv_model.alpha_

0.1

In [56]:
from sklearn.metrics import SCORERS

In [57]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [58]:
test_pred = ridgecv_model.predict(X_test)

In [59]:
MAE = mean_absolute_error(y_test,test_pred)

In [60]:
MAE

0.42737748843414897

In [61]:
MSE = mean_squared_error(y_test,test_pred)

In [62]:
MSE

0.3820129881538343

In [63]:
RMSE = np.sqrt(MSE)

In [64]:
RMSE

0.6180719926948917

In [66]:
from sklearn.linear_model import LassoCV

In [130]:
lasso_cv = LassoCV(eps=0.01 ,n_alphas=100,cv = 5, max_iter= 100000)

In [131]:
lasso_cv.fit(X_train,y_train)

LassoCV(cv=5, eps=0.01, max_iter=100000)

In [132]:
lasso_cv.alpha_

0.049430709092258274

In [133]:
test_pr = lasso_cv.predict(X_test)

In [134]:
MAE= mean_absolute_error(y_test,test_pr)

In [135]:
MSE = mean_squared_error(y_test,test_pr)

In [136]:
RMSE = np.sqrt(MSE)

In [137]:
MAE

0.5159788188265407

In [138]:
MSE

0.5799493101252955

In [139]:
RMSE

0.761544030326084

In [140]:
lasso_cv.coef_

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [141]:
from sklearn.linear_model import ElasticNetCV

In [142]:
elasticM = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001, max_iter=100000,n_alphas=100)

In [143]:
elasticM.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [145]:
elasticM.l1_ratio_

1.0

In [146]:
elasticM.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [147]:
elasticM.alpha_

0.004943070909225827

In [148]:
lasso_cv.alpha_

0.049430709092258274

In [149]:
test_p = elasticM.predict(X_test)

In [150]:
MAE= mean_absolute_error(y_test,test_p)
MSE = mean_squared_error(y_test,test_p)
RMSE = np.sqrt(MSE)

In [151]:
MAE

0.4335034618590069

In [152]:
MSE

0.36761675741990574

In [153]:
RMSE

0.6063140748984026