In [1]:
import numpy as np

In [4]:
arr  = np.arange(0,11)

In [5]:
arr[0]

0

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[2:5:2]

array([2, 4])

In [10]:
arr[5]

5

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
# broadcasting

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#here array are linking together , change in one will change the other
slice_of_arr = arr[:5]

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_arr[:] = 99

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
slice_of_arr = arr.copy()[:5]

In [27]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [28]:
slice_of_arr[:] = 100

In [29]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [30]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [39]:
a = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [40]:
a


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
a.shape

(3, 3)

In [42]:
a[2]

array([35, 40, 45])

In [43]:
a[2][1]

40

In [44]:
a[2,1]

40

In [50]:
a[:2,1:]

array([[10, 15],
       [25, 30]])

In [51]:
arr = np.arange(0,10)

In [52]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
bool_arr = arr>4

In [54]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [56]:
arr[arr>4]

array([5, 6, 7, 8, 9])