In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3, 4])

In [5]:
type(mylist)

list

In [6]:
mylist


[1, 2, 3, 4]

In [9]:
myarr = np.array(mylist)

In [10]:
myarr


array([1, 2, 3, 4])

In [11]:
type(myarr)

numpy.ndarray

In [17]:
my_matrix = [[1,2,3],[5,6,7],[8,9,0]]

In [18]:
np.array(my_matrix)

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [16]:
my_matrix

[[1, 2, 3], [5, 6, 7], [8, 9, 0]]

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:

np.linspace(0,10,123)

array([ 0.        ,  0.08196721,  0.16393443,  0.24590164,  0.32786885,
        0.40983607,  0.49180328,  0.57377049,  0.6557377 ,  0.73770492,
        0.81967213,  0.90163934,  0.98360656,  1.06557377,  1.14754098,
        1.2295082 ,  1.31147541,  1.39344262,  1.47540984,  1.55737705,
        1.63934426,  1.72131148,  1.80327869,  1.8852459 ,  1.96721311,
        2.04918033,  2.13114754,  2.21311475,  2.29508197,  2.37704918,
        2.45901639,  2.54098361,  2.62295082,  2.70491803,  2.78688525,
        2.86885246,  2.95081967,  3.03278689,  3.1147541 ,  3.19672131,
        3.27868852,  3.36065574,  3.44262295,  3.52459016,  3.60655738,
        3.68852459,  3.7704918 ,  3.85245902,  3.93442623,  4.01639344,
        4.09836066,  4.18032787,  4.26229508,  4.3442623 ,  4.42622951,
        4.50819672,  4.59016393,  4.67213115,  4.75409836,  4.83606557,
        4.91803279,  5.        ,  5.08196721,  5.16393443,  5.24590164,
        5.32786885,  5.40983607,  5.49180328,  5.57377049,  5.65

In [35]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.random.rand(5,2)

array([[0.14580789, 0.26789568],
       [0.16602265, 0.99691742],
       [0.55309947, 0.90882346],
       [0.80248757, 0.93503143],
       [0.81725426, 0.03005861]])

In [47]:
np.random.randn(7,3)

array([[ 0.93919618,  0.40454115, -0.58823256],
       [ 1.68650499,  0.54309794, -0.23160545],
       [-0.22495652, -0.87130958, -0.27042161],
       [-0.30841313, -1.05931707,  0.67349786],
       [-0.04856123,  0.2549635 ,  0.12631952],
       [ 1.79760393,  0.16080162, -0.09311485],
       [ 0.2201859 ,  0.83958508,  0.75068537]])

In [55]:
np.random.randint(1,1000,(4,5))

array([[572,  20,  19, 813, 624],
       [596, 835, 734, 196, 503],
       [ 59, 679, 668, 846, 597],
       [818, 367, 907, 283, 342]])

In [65]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [66]:
arr = np.arange(0,25)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
ran = np.random.randint(0,101,10)

In [73]:
ran

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [75]:
ran.max()

99

In [76]:
ran.min()

2

In [77]:
ran.argmin()

7

In [78]:
ran.argmax()

5

In [80]:
ran.dtype

dtype('int32')

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
arr.shape

(25,)

In [85]:
arr  = arr.reshape(5,5)

In [86]:
arr.shape

(5, 5)