In [1]:
import numpy as np

In [2]:
a = np.arange(0,10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
a/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a+4/3*13-4

array([13.33333333, 14.33333333, 15.33333333, 16.33333333, 17.33333333,
       18.33333333, 19.33333333, 20.33333333, 21.33333333, 22.33333333])

In [10]:
a/a

C:\Users\kanis\AppData\Local\Temp\ipykernel_24228\2959643021.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
a**a

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [12]:
1/a

C:\Users\kanis\AppData\Local\Temp\ipykernel_24228\261954055.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
b= np.arange(0,15)

In [14]:
a+b

ValueError: operands could not be broadcast together with shapes (10,) (15,) 

In [15]:
a*b

ValueError: operands could not be broadcast together with shapes (10,) (15,) 

In [16]:
a+b

ValueError: operands could not be broadcast together with shapes (10,) (15,) 

In [17]:
b=np.arange(0,10)

In [18]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a+b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
a = a+b

In [21]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
a-b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.sqrt(a)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [24]:
np.sin(a)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [25]:
np.log(a)

C:\Users\kanis\AppData\Local\Temp\ipykernel_24228\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176])

In [26]:
a.sum()

90

In [27]:
a.mean()

9.0

In [28]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [29]:
a.var()

33.0

In [30]:
a.max()

18

In [31]:
a.std()

5.744562646538029

In [34]:
arr2d = np.arange(0,25).reshape(5,5)

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr2d.sum()

300

In [40]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])